// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjVl3v3nq2HSH2M-eKUpWYf1keuRBzIDc',
    appId: '1:67003153024:web:58f987d5e42d60a66d4465',
    messagingSenderId: '67003153024',
    projectId: 'to-do-app-da69f',
    authDomain: 'to-do-app-da69f.firebaseapp.com',
    storageBucket: 'to-do-app-da69f.firebasestorage.app',
    measurementId: 'G-LN7CTVHJJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbvpaqu3gSA4PLSM5KS097LW75pMWm4VI',
    appId: '1:67003153024:android:e6f61c684e00c2d76d4465',
    messagingSenderId: '67003153024',
    projectId: 'to-do-app-da69f',
    storageBucket: 'to-do-app-da69f.firebasestorage.app',
  );
}